####################################################
# namespace
####################################################
apiVersion: v1
kind: Namespace
metadata:
  name: sb-tracing-demo
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: sb-tracing-demo
data:
  JAEGER_UDP_SENDER_HOST: jaeger-agent.istio-system.svc.cluster.local
  REDIS_HOST: redis-master