---
apiVersion: v1
kind: Service
metadata:
  namespace: sb-tracing-demo
  name: foo-svc
  labels:
    app: foo-svc
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: foo-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-svc
  namespace: sb-tracing-demo
spec:
  selector:
    matchLabels:
      app: foo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: foo-svc
    spec:
      volumes:
        - name: agent
          emptyDir: {}
      initContainers:
        - name: agent
          image: apache/skywalking-java-agent:8.11.0-java8
          command:
            - /bin/sh
          args:
            - '-c'
            - cp -R /skywalking/agent /sidecar/
          resources: {}
          volumeMounts:
            - name: agent
              mountPath: /sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
      - name: foo-svc
        image: taloricag/sb-agent-demo-foo-svc:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: JVM_OPTS
            value: "-Xms256m -Xmx256m"
          - name: JAVA_ARGS
            value: >-
              -javaagent:/sidecar/agent/skywalking-agent.jar
              -Dskywalking.agent.service_name=foo-svc
              -Dskywalking.collector.backend_service=otel-collector.open-telemetry:11800
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
          - name: agent
            mountPath: /sidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-svc
  namespace: sb-tracing-demo
spec:
  selector:
    matchLabels:
      app: foo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: foo-svc
    spec:
      volumes:
        - name: agent
          emptyDir: {}
      initContainers:
        - name: agent
          image: taloricag/opentelemetry-javaagent:1.31.0
          command:
            - /bin/sh
          args:
            - '-c'
            - cp -R /opentelemetry/agent /sidecar/
          resources: {}
          volumeMounts:
            - name: agent
              mountPath: /sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: pscope
          image: taloricag/pyroscope-agent:v0.12.2
          command:
            - /bin/sh
          args:
            - '-c'
            - cp -R /pyroscope/agent/ /sidecar/
          resources: {}
          volumeMounts:
            - name: agent
              mountPath: /sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
      - name: foo-svc
        image: ${image_repo}/springboot-foo-svc:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: JVM_OPTS
            value: "-Xms256m -Xmx256m"
          - name: PYROSCOPE_APPLICATION_NAME
            value: java-foo-svc
          - name: PYROSCOPE_EXPORT_COMPRESSION_LEVEL_JFR
            value: '0'
          - name: PYROSCOPE_EXPORT_COMPRESSION_LEVEL_LABELS
            value: '0'
          - name: JAVA_ARGS
            value: >-
              -javaagent:/sidecar/agent/opentelemetry-javaagent.jar
              -javaagent:/sidecar/agent/pyroscope.jar
              -Dotel.resource.attributes=service.name=foo-svc
              -Dotel.traces.exporter=otlp -XX:+PreserveFramePointer
              -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.open-telemetry:4317
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
          - name: agent
            mountPath: /sidecar
