---
apiVersion: v1
kind: Service
metadata:
  namespace: sb-tracing-demo
  name: loo-svc
  labels:
    app: loo-svc
spec:
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loo-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loo-svc
  namespace: sb-tracing-demo
spec:
  selector:
    matchLabels:
      app: loo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: loo-svc
    spec:
      volumes:
        - name: agent
          emptyDir: {}
      initContainers:
        - name: agent
          image: apache/skywalking-java-agent:8.11.0-java8
          command:
            - /bin/sh
          args:
            - '-c'
            - cp -R /skywalking/agent /sidecar/
          resources: {}
          volumeMounts:
            - name: agent
              mountPath: /sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
      - name: loo-svc
        image: taloricag/sb-agent-demo-loo-svc:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: JVM_OPTS
            value: "-Xms256m -Xmx256m"
          - name: JAVA_ARGS
            value: >-
              -javaagent:/sidecar/agent/skywalking-agent.jar
              -Dskywalking.agent.service_name=loo-svc
              -Dskywalking.collector.backend_service=otel-collector.open-telemetry:11800
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
          - name: agent
            mountPath: /sidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loo-svc
  namespace: sb-tracing-demo
spec:
  selector:
    matchLabels:
      app: loo-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: loo-svc
    spec:
      volumes:
        - name: agent
          emptyDir: {}
      initContainers:
        - name: agent
          image: taloricag/opentelemetry-javaagent:1.15.0
          command:
            - /bin/sh
          args:
            - '-c'
            - cp -R /opentelemetry/agent /sidecar/
          resources: {}
          volumeMounts:
            - name: agent
              mountPath: /sidecar
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
      - name: loo-svc
        image: taloricag/sb-agent-demo-loo-svc:0.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
          - name: JVM_OPTS
            value: "-Xms256m -Xmx256m"
          - name: JAVA_ARGS
            value: >-
              -javaagent:/sidecar/agent/opentelemetry-javaagent.jar
              -Dotel.resource.attributes=service.name=loo-svc
              -Dotel.traces.exporter=otlp
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://otel-collector.open-telemetry:4317
        envFrom:
        - configMapRef:
            name: demo-config
        volumeMounts:
          - name: agent
            mountPath: /sidecar
